# Generated by Django 3.2.13 on 2022-06-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('website', models.URLField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('officeextension', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('roll', models.CharField(max_length=100)),
            ],
        ),
    ]
